import { v4 as uuidV4, validate as uuidValidate } from "uuid";
import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Box, Button, Flex, Heading, Text, Input, Divider, Stack, useToast } from "@chakra-ui/react";
import { ArrowForwardIcon, AddIcon } from "@chakra-ui/icons";
import { motion } from "framer-motion";

export default function Preview() {
  const docId = uuidV4();
  const navigate = useNavigate();
  const [roomId, setRoomId] = useState("");
  const toast = useToast();

  const joinRoomViaRoomId = () => {
    if (!roomId.trim()) return;

    let idToValidate = roomId.trim();

    // Extract ID from URL if user pastes a full link
    if (idToValidate.includes("http") || idToValidate.includes("https")) {
      try {
        const url = new URL(idToValidate);
        const parts = url.pathname.split('/').filter(Boolean);
        idToValidate = parts[parts.length - 1] || "";
      } catch (e) {
        toast({
          title: "Invalid URL",
          description: "Please enter a valid room URL.",
          status: "error",
          duration: 3000,
          isClosable: true,
          position: "top",
        });
        return;
      }
    }

    // Authenticate if the Room ID is actually a valid UUID generated by our system
    if (!uuidValidate(idToValidate)) {
      toast({
        title: "Room Not Found",
        description: "The Room ID you entered does not exist or is invalid.",
        status: "error",
        duration: 3000,
        isClosable: true,
        position: "top",
      });
      return;
    }

    if (roomId.includes("http") || roomId.includes("https")) {
      const url = new URL(roomId);
      navigate(url.pathname);
    } else {
      navigate(`./${roomId}`);
    }
  };

  return (
    <Flex
      justifyContent={"center"}
      alignItems={"center"}
      minH={"calc(100vh - 70px)"}
      backgroundPosition={"center"}
      backgroundRepeat={"no-repeat"}
      backgroundSize={"cover"}
      position={"relative"}
      backgroundImage={"url(/mockBG.jpeg)"}
    >
      {/* Dark overlay for text contrast and premium feel */}
      <Box
        position="absolute"
        top={0}
        left={0}
        right={0}
        bottom={0}
        bg="rgba(10, 15, 26, 0.85)"
        backdropFilter="blur(12px)"
        zIndex={0}
      />

      <Flex
        direction="column"
        align="center"
        justify="center"
        zIndex={1}
        w="full"
        px={4}
      >
        <Box
          as={motion.div}
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, ease: "easeOut" }}
          textAlign="center"
          mb={10}
        >
          <Heading
            as="h1"
            fontSize={{ base: "4xl", md: "5xl", lg: "6xl" }}
            fontWeight="extrabold"
            letterSpacing="tight"
            color="white"
            mb={4}
          >
            The Code{" "}
            <Text
              as="span"
              bgGradient="linear(to-r, purple.300, pink.400)"
              bgClip="text"
            >
              Arena
            </Text>
          </Heading>
          <Text fontSize={{ base: "md", md: "lg" }} color="gray.400" maxW="lg" mx="auto">
            Launch a real-time coding environment or enter an active arena to begin peer-to-peer coding.
          </Text>
        </Box>

        <Box
          as={motion.div}
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.5, delay: 0.2, ease: "easeOut" }}
          bg="rgba(255, 255, 255, 0.03)"
          border="1px solid"
          borderColor="whiteAlpha.200"
          backdropFilter="blur(16px)"
          rounded="3xl"
          p={{ base: 6, md: 10 }}
          w="full"
          maxW="md"
          boxShadow="0 25px 50px -12px rgba(0, 0, 0, 0.5)"
        >
          <Stack spacing={8}>
            <Box>
              <Text color="white" fontWeight="semibold" mb={4} fontSize="lg">
                Initialize a New Collaborative Arena
              </Text>
              <Button
                w="full"
                size="lg"
                rounded="xl"
                colorScheme="purple"
                bgGradient="linear(to-r, purple.400, purple.500)"
                color="white"
                leftIcon={<AddIcon />}
                _hover={{
                  transform: "translateY(-2px)",
                  boxShadow: "0 10px 20px -10px rgba(159,122,234,0.7)",
                  bgGradient: "linear(to-r, purple.500, purple.600)"
                }}
                transition="all 0.2s"
                onClick={() => navigate(`./${docId}`)}
              >
                Open New Arena
              </Button>
            </Box>

            <Flex align="center">
              <Divider borderColor="whiteAlpha.300" />
              <Text px={4} color="gray.500" fontSize="sm" fontWeight="medium">
                OR
              </Text>
              <Divider borderColor="whiteAlpha.300" />
            </Flex>

            <Box>
              <Text color="white" fontWeight="semibold" mb={4} fontSize="lg">
                Join an Existing Active Arena
              </Text>
              <Stack spacing={4}>
                <Input
                  value={roomId}
                  onChange={(e) => setRoomId(e.target.value)}
                  placeholder="Paste Arena Access Key or URL"
                  size="lg"
                  bg="rgba(0, 0, 0, 0.2)"
                  border="1px solid"
                  borderColor="whiteAlpha.200"
                  color="white"
                  rounded="xl"
                  _placeholder={{ color: "gray.500" }}
                  _hover={{ borderColor: "whiteAlpha.400" }}
                  _focus={{
                    borderColor: "purple.400",
                    boxShadow: "0 0 0 1px #9f7aea",
                    bg: "rgba(0, 0, 0, 0.3)",
                  }}
                  onKeyDown={(e) => {
                    if (e.key === "Enter") joinRoomViaRoomId();
                  }}
                />
                <Button
                  w="full"
                  size="lg"
                  rounded="xl"
                  variant="outline"
                  color="white"
                  borderColor="whiteAlpha.500"
                  rightIcon={<ArrowForwardIcon />}
                  _hover={{
                    bg: "whiteAlpha.200",
                    borderColor: "white",
                  }}
                  transition="all 0.2s"
                  onClick={joinRoomViaRoomId}
                  isDisabled={!roomId.trim()}
                >
                  Enter Arena
                </Button>
              </Stack>
            </Box>
          </Stack>
        </Box>
      </Flex>
    </Flex>
  );
}
